### ISSUE TITLE
add docs for the new __view__ attribute

### ISSUE THREAD

**Issue by iandouglas** [jeffknupp/sandman#53]
Reference: https://github.com/jeffknupp/sandman/pull/41

Any chance we can get something added to the docs for this? I'm not sure I understand how to use this attribute. I've tried making a model view based on Flask-Admin's BaseView class, and making that available to my model:

```
from sandman.model import Model
from flask.ext.admin import BaseView, expose

class FooView(BaseView):
@expose('/')
    def index(self):
        return self.render('index.html')

class Foo(Model):
    __tablename__ = 'foo'
    __view__ = FooView

```

The next result is a dropdown menu on my navbar which says '<sqlalchemy.orm.scoped_session object at 0x.....> with a submenu item which says <class 'models.Foo'> ... and clicking on it throws a 500 error for a TemplateNotFound (index.html) exception.

**Comment by jeffknupp** [comment]
I'll be adding something to the docs for this, but basically there's no
easy way to access the AdminView from the sandman Model. I'll be making
this interaction easier/possible in the near future,

**Comment by jeffknupp** [comment]
Not that the issue here is that you need to derive from `flask.ext.admin.contrib.sqla.ModelView` rather than `BaseView`. Exposing non-model endpoints is outside of the scope of `sandman`.

The way `__view__` works is if you want to customize something in the admin (say, use a different template for a particular model), you create a class that inherits from `ModelView`, add whatever property you want, then set that as the value for `__view__` on the given model. For example:

```
class NewTrackTemplate(ModelView):
    list_template = 'my_new_template.html'

class Track(Model):
     __tablename__ = 'Track'
     __view__ = NewTrackTemplate
```

Hope that clears things up a bit.
